server:
  port: 8080

#logging:
#  file: D:/Cognizant-Course/Assignment/assignment-2/assignment-exercise-two/logs/info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tweet_application?autoReconnect=true&useUnicode=yes&useSSL=false&serverTimezone=UTC
    username: root
    password: Matlab009cxnakhi123

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
